site_name: API License Documentation
site_description: Documentation for the License Management API
site_author: Karned
site_url: https://USERNAME.github.io/api-license/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true

nav:
  - Home: index.md
  - API Overview: api-overview.md
  - Authentication: authentication.md
  - Endpoints:
    - Items: endpoints/items.md
  - Models:
    - Item: models/item.md
  - Installation: installation.md
